package model.entity;
// Generated 1 nov. 2016 10:44:10 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ClSubstance generated by hbm2java
 */
@Entity
@Table(name = "cl_biomarker", schema = "epimed_semantic")
public class ClBiomarker implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String biomarker;

	public ClBiomarker() {
	}

	public ClBiomarker(String biomarker) {
		this.biomarker = biomarker;
	}

	@Id

	@Column(name = "biomarker", unique = true, nullable = false, length = 50)
	public String getBiomarker() {
		return this.biomarker;
	}

	public void setBiomarker(String biomarker) {
		this.biomarker = biomarker;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((biomarker == null) ? 0 : biomarker.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ClBiomarker other = (ClBiomarker) obj;
		if (biomarker == null) {
			if (other.biomarker != null)
				return false;
		} else if (!biomarker.equals(other.biomarker))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ClBiomarker [biomarker=" + biomarker + "]";
	}
	
}
