package model.entity;
// Generated 1 nov. 2016 10:44:10 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClTopologyGroup generated by hbm2java
 */
@Entity
@Table(name = "cl_epimed_group", schema = "epimed_semantic")
public class ClEpimedGroup implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idEpimedGroup;
	private ClEpimedGroup parent;
	private String name;
	private Integer level;

	public ClEpimedGroup() {
	}


	public ClEpimedGroup(Integer idEpimedGroup, ClEpimedGroup parent, String name, Integer level) {
		super();
		this.idEpimedGroup = idEpimedGroup;
		this.parent = parent;
		this.name = name;
		this.level = level;
	}



	@Id

	@Column(name = "id_epimed_group", unique = true, nullable = false, length = 100)
	public Integer getIdEpimedGroup() {
		return this.idEpimedGroup;
	}

	public void setIdEpimedGroup(Integer idEpimedGroup) {
		this.idEpimedGroup = idEpimedGroup;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_parent", nullable = true)
	public ClEpimedGroup getParent() {
		return this.parent;
	}

	public void setParent(ClEpimedGroup parent) {
		this.parent = parent;
	}


	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	@Column(name = "level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}


	@Override
	public String toString() {
		return "ClEpimedGroup [idEpimedGroup=" + idEpimedGroup + ", parent=" + parent + ", name=" + name + ", level="
				+ level + "]";
	}

}
