package model.entity;
// Generated 1 nov. 2016 10:44:10 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClOntologyDictionary generated by hbm2java
 */
@Entity
@Table(name = "cl_ontology_dictionary", schema = "epimed_semantic")
public class ClOntologyDictionary implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ClOntologyDictionaryId id;
	private ClOntologyCategory clOntologyCategory;
	private String idReference;

	public ClOntologyDictionary() {
	}

	public ClOntologyDictionary(ClOntologyDictionaryId id, ClOntologyCategory clOntologyCategory, String idReference) {
		this.id = id;
		this.clOntologyCategory = clOntologyCategory;
		this.idReference = idReference;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "term", column = @Column(name = "term", nullable = false)),
			@AttributeOverride(name = "idCategory", column = @Column(name = "id_category", nullable = false, length = 100)) })
	public ClOntologyDictionaryId getId() {
		return this.id;
	}

	public void setId(ClOntologyDictionaryId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_category", nullable = false, insertable = false, updatable = false)
	public ClOntologyCategory getClOntologyCategory() {
		return this.clOntologyCategory;
	}

	public void setClOntologyCategory(ClOntologyCategory clOntologyCategory) {
		this.clOntologyCategory = clOntologyCategory;
	}

	@Column(name = "id_reference", nullable = false, length = 50)
	public String getIdReference() {
		return this.idReference;
	}

	public void setIdReference(String idReference) {
		this.idReference = idReference;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ClOntologyDictionary other = (ClOntologyDictionary) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ClOntologyDictionary [id=" + id + ", clOntologyCategory=" + clOntologyCategory + ", idReference="
				+ idReference + "]";
	}

	
	
}
