package model.entity;
// Generated 1 nov. 2016 10:44:10 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClOntologyKeywordId generated by hbm2java
 */
@Embeddable
public class ClOntologyKeywordId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idKeyword;
	private String idCategory;

	public ClOntologyKeywordId() {
	}

	public ClOntologyKeywordId(String idKeyword, String idCategory) {
		this.idKeyword = idKeyword;
		this.idCategory = idCategory;
	}

	@Column(name = "id_keyword", nullable = false)
	public String getIdKeyword() {
		return this.idKeyword;
	}

	public void setIdKeyword(String idKeyword) {
		this.idKeyword = idKeyword;
	}

	@Column(name = "id_category", nullable = false, length = 100)
	public String getIdCategory() {
		return this.idCategory;
	}

	public void setIdCategory(String idCategory) {
		this.idCategory = idCategory;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClOntologyKeywordId))
			return false;
		ClOntologyKeywordId castOther = (ClOntologyKeywordId) other;

		return ((this.getIdKeyword() == castOther.getIdKeyword()) || (this.getIdKeyword() != null
				&& castOther.getIdKeyword() != null && this.getIdKeyword().equals(castOther.getIdKeyword())))
				&& ((this.getIdCategory() == castOther.getIdCategory())
						|| (this.getIdCategory() != null && castOther.getIdCategory() != null
								&& this.getIdCategory().equals(castOther.getIdCategory())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdKeyword() == null ? 0 : this.getIdKeyword().hashCode());
		result = 37 * result + (getIdCategory() == null ? 0 : this.getIdCategory().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "ClOntologyKeywordId [idKeyword=" + idKeyword + ", idCategory=" + idCategory + "]";
	}
	
	

}
