package model.entity;
// Generated 1 nov. 2016 10:44:10 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClOntologyDictionaryId generated by hbm2java
 */
@Embeddable
public class ClOntologyDictionaryId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String term;
	private String idCategory;

	public ClOntologyDictionaryId() {
	}

	public ClOntologyDictionaryId(String term, String idCategory) {
		this.term = term;
		this.idCategory = idCategory;
	}

	@Column(name = "term", nullable = false)
	public String getTerm() {
		return this.term;
	}

	public void setTerm(String term) {
		this.term = term;
	}

	@Column(name = "id_category", nullable = false, length = 100)
	public String getIdCategory() {
		return this.idCategory;
	}

	public void setIdCategory(String idCategory) {
		this.idCategory = idCategory;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClOntologyDictionaryId))
			return false;
		ClOntologyDictionaryId castOther = (ClOntologyDictionaryId) other;

		return ((this.getTerm() == castOther.getTerm()) || (this.getTerm() != null && castOther.getTerm() != null
				&& this.getTerm().equals(castOther.getTerm())))
				&& ((this.getIdCategory() == castOther.getIdCategory())
						|| (this.getIdCategory() != null && castOther.getIdCategory() != null
								&& this.getIdCategory().equals(castOther.getIdCategory())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTerm() == null ? 0 : this.getTerm().hashCode());
		result = 37 * result + (getIdCategory() == null ? 0 : this.getIdCategory().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "ClOntologyDictionaryId [term=" + term + ", idCategory=" + idCategory + "]";
	}
	
	

}
