package model.entity;
// Generated 1 nov. 2016 10:44:10 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ClPathology generated by hbm2java
 */
@Entity
@Table(name = "cl_pathology", schema = "epimed_semantic")
public class ClPathology implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idPathology;
	private String code;
	private String name;

	public ClPathology() {
	}

	public ClPathology(String idPathology, String name) {
		this.idPathology = idPathology;
		this.name = name;
	}

	public ClPathology(String idPathology, String code, String name) {
		this.idPathology = idPathology;
		this.code = code;
		this.name = name;
	}

	@Id

	@Column(name = "id_pathology", unique = true, nullable = false, length = 20)
	public String getIdPathology() {
		return this.idPathology;
	}

	public void setIdPathology(String idPathology) {
		this.idPathology = idPathology;
	}

	@Column(name = "code", length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idPathology == null) ? 0 : idPathology.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ClPathology other = (ClPathology) obj;
		if (idPathology == null) {
			if (other.idPathology != null)
				return false;
		} else if (!idPathology.equals(other.idPathology))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ClPathology [idPathology=" + idPathology + ", code=" + code + ", name=" + name + "]";
	}
	
	

}
