package model.entity;
// Generated 1 nov. 2016 10:44:10 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ClTissueStatus generated by hbm2java
 */
@Entity
@Table(name = "cl_tissue_status", schema = "epimed_semantic")
public class ClTissueStatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTissueStatus;
	private String name;

	public ClTissueStatus() {
	}

	public ClTissueStatus(Integer idTissueStatus, String name) {
		this.idTissueStatus = idTissueStatus;
		this.name = name;
	}

	@Id

	@Column(name = "id_tissue_status", unique = true, nullable = false)
	public Integer getIdTissueStatus() {
		return this.idTissueStatus;
	}

	public void setIdTissueStatus(Integer idTissueStatus) {
		this.idTissueStatus = idTissueStatus;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idTissueStatus == null) ? 0 : idTissueStatus.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ClTissueStatus other = (ClTissueStatus) obj;
		if (idTissueStatus == null) {
			if (other.idTissueStatus != null)
				return false;
		} else if (!idTissueStatus.equals(other.idTissueStatus))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ClTissueStatus [idTissueStatus=" + idTissueStatus + ", name=" + name + "]";
	}
	
	

}
