package model.entity;
// Generated 1 nov. 2016 10:44:10 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClTopology generated by hbm2java
 */
@Entity
@Table(name = "cl_topology", schema = "epimed_semantic")
public class ClTopology implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idTopology;
	private ClTopologyGroup clTopologyGroup;
	private String name;
	private Set<ClCellLine> clCellLines = new HashSet<ClCellLine>(0);

	public ClTopology() {
	}

	public ClTopology(String idTopology, ClTopologyGroup clTopologyGroup, String name) {
		this.idTopology = idTopology;
		this.clTopologyGroup = clTopologyGroup;
		this.name = name;
	}

	public ClTopology(String idTopology, ClTopologyGroup clTopologyGroup, String name, Set<ClCellLine> clCellLines) {
		this.idTopology = idTopology;
		this.clTopologyGroup = clTopologyGroup;
		this.name = name;
		this.clCellLines = clCellLines;
	}

	@Id

	@Column(name = "id_topology", unique = true, nullable = false, length = 10)
	public String getIdTopology() {
		return this.idTopology;
	}

	public void setIdTopology(String idTopology) {
		this.idTopology = idTopology;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_group", nullable = false)
	public ClTopologyGroup getClTopologyGroup() {
		return this.clTopologyGroup;
	}

	public void setClTopologyGroup(ClTopologyGroup clTopologyGroup) {
		this.clTopologyGroup = clTopologyGroup;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clTopology")
	public Set<ClCellLine> getClCellLines() {
		return this.clCellLines;
	}

	public void setClCellLines(Set<ClCellLine> clCellLines) {
		this.clCellLines = clCellLines;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idTopology == null) ? 0 : idTopology.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ClTopology other = (ClTopology) obj;
		if (idTopology == null) {
			if (other.idTopology != null)
				return false;
		} else if (!idTopology.equals(other.idTopology))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ClTopology [idTopology=" + idTopology + ", clTopologyGroup=" + clTopologyGroup + ", name=" + name + "]";
	}
	
	
	

}
