package model.entity;
// Generated 1 nov. 2016 10:44:10 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ClTreatmentMethod generated by hbm2java
 */
@Entity
@Table(name = "cl_treatment_method", schema = "epimed_semantic")
public class ClTreatmentMethod implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTreatmentMethod;
	private String name;

	public ClTreatmentMethod() {
	}

	public ClTreatmentMethod(Integer idTreatmentMethod, String name) {
		this.idTreatmentMethod = idTreatmentMethod;
		this.name = name;
	}

	@Id

	@Column(name = "id_treatment_method", unique = true, nullable = false)
	public Integer getIdTreatmentMethod() {
		return this.idTreatmentMethod;
	}

	public void setIdTreatmentMethod(Integer idTreatmentMethod) {
		this.idTreatmentMethod = idTreatmentMethod;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idTreatmentMethod == null) ? 0 : idTreatmentMethod.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ClTreatmentMethod other = (ClTreatmentMethod) obj;
		if (idTreatmentMethod == null) {
			if (other.idTreatmentMethod != null)
				return false;
		} else if (!idTreatmentMethod.equals(other.idTreatmentMethod))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ClTreatmentMethod [idTreatmentMethod=" + idTreatmentMethod + ", name=" + name + "]";
	}
	
	

}
