package model.entity;
// Generated 16 mars 2017 10:27:56 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OmGenbankUnigene generated by hbm2java
 */
@Entity
@Table(name = "om_genbank_unigene", schema = "hs")
public class OmGenbankUnigene implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String genbankAcc;
	private OmUnigene omUnigene;
	private Date lastUpdate;

	public OmGenbankUnigene() {
	}

	public OmGenbankUnigene(String genbankAcc) {
		this.genbankAcc = genbankAcc;
	}

	public OmGenbankUnigene(String genbankAcc, OmUnigene omUnigene, Date lastUpdate) {
		this.genbankAcc = genbankAcc;
		this.omUnigene = omUnigene;
		this.lastUpdate = lastUpdate;
	}

	@Id

	@Column(name = "genbank_acc", unique = true, nullable = false, length = 50)
	public String getGenbankAcc() {
		return this.genbankAcc;
	}

	public void setGenbankAcc(String genbankAcc) {
		this.genbankAcc = genbankAcc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_unigene")
	public OmUnigene getOmUnigene() {
		return this.omUnigene;
	}

	public void setOmUnigene(OmUnigene omUnigene) {
		this.omUnigene = omUnigene;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_update", length = 13)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((genbankAcc == null) ? 0 : genbankAcc.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OmGenbankUnigene other = (OmGenbankUnigene) obj;
		if (genbankAcc == null) {
			if (other.genbankAcc != null)
				return false;
		} else if (!genbankAcc.equals(other.genbankAcc))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "OmGenbankUnigene [genbankAcc=" + genbankAcc + ", lastUpdate=" + lastUpdate + "]";
	}
	
	

}
