package model.entity;
// Generated 1 nov. 2016 10:44:10 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewOntologyDictionary generated by hbm2java
 */
@Entity
@Table(name = "view_ontology_dictionary", schema = "epimed_semantic")
public class ViewOntologyDictionary implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ViewOntologyDictionaryId id;

	public ViewOntologyDictionary() {
	}

	public ViewOntologyDictionary(ViewOntologyDictionaryId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "term", column = @Column(name = "term")),
			@AttributeOverride(name = "idReference", column = @Column(name = "id_reference")),
			@AttributeOverride(name = "idCategory", column = @Column(name = "id_category")) })
	public ViewOntologyDictionaryId getId() {
		return this.id;
	}

	public void setId(ViewOntologyDictionaryId id) {
		this.id = id;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ViewOntologyDictionary other = (ViewOntologyDictionary) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ViewOntologyDictionary [id=" + id + "]";
	}

	
	
}
